### PR TITLE
cicd: test Cuda version supported by Kokkos (11.0.3)

### PR DESCRIPTION
**Pull request by romintomasetti**
As requested by @crtrott in https://github.com/kokkos/kokkos-tools/pull/211#issuecomment-1749332578.

The closest to `11.0` in the Docker hub is `11.0.3`.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Wow you are fast! Thanks so much!

**Review by masterleinad — APPROVED** [review]

**Comment by romintomasetti** [comment]
I needed to set `DEBIAN_FRONTEND=noninteractive` in other to avoid prompts with this image (`nvidia/cuda:11.0.3-devel-ubuntu20.04`) :scroll:

**Comment by romintomasetti** [comment]
Yet another problem: `CMake` version in `Ubuntu 20.04` is `3.16`. It does not support JSON presets yet.

So I added the Kitware APT stuff.

But all the Kitware websites are down for now... https://downforeveryoneorjustme.com/cmake.org

**Comment by romintomasetti** [comment]
Seems like something is wrong in the `perfetto` connector.

https://github.com/kokkos/kokkos-tools/actions/runs/6432156094/job/17466419907

Edit: @crtrott Any idea? :smile:

**Comment by crtrott** [comment]
Not sure might be a problem with specific compiler combos. I can check

**Comment by vlkale** [comment]
@crtrott @romintomasetti Just checking on the status of this. 

Looking at this, I don't think it is a blocker for other Kokkos Tools PRs and it is a nice-to-have.

**Comment by vlkale** [comment]
> Seems like something is wrong in the `perfetto` connector.
> 
> 
> 
> https://github.com/kokkos/kokkos-tools/actions/runs/6432156094/job/17466419907
> 
> 
> 
> Edit: @crtrott Any idea? :smile:


OTOH, I think we should get this PR handled soon, especially if there are Kokkos applications that currently are depending on the Perfetto connector.

**Comment by crtrott** [comment]
Rebase in #271

**Pull request closed without merging**
