### PR TITLE
Space time: Adding space labels

### PR DESCRIPTION
**Pull request by csiefer2**
This will allow people to find host-device and device-host transfers just by looking at the space time stack

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks reasonable to me but it seems that you need to fix the indentation.

**Comment by csiefer2** [comment]
@masterleinad Which part is indented incorrectly?  I thought I followed the style in the file...

**Comment by masterleinad** [comment]
> @masterleinad Which part is indented incorrectly? I thought I followed the style in the file...

Using `clang-format-8`, I get
```diff
diff --git a/profiling/space-time-stack/kp_space_time_stack.cpp b/profiling/space-time-stack/kp_space_time_stack.cpp
index b1e6835..be127ed 100644
--- a/profiling/space-time-stack/kp_space_time_stack.cpp
+++ b/profiling/space-time-stack/kp_space_time_stack.cpp
@@ -711,8 +711,9 @@ struct State {
     current_allocations[space].deallocate(std::string(name), ptr, size,
                                           stack_frame);
   }
-  void begin_deep_copy(Space dst_space, const char* dst_name, const void*, Space src_space,
-                       const char* src_name, const void*, std::uint64_t) {
+  void begin_deep_copy(Space dst_space, const char* dst_name, const void*,
+                       Space src_space, const char* src_name, const void*,
+                       std::uint64_t) {
     std::string frame_name;
     frame_name += "\"";
     frame_name += dst_name;
```

**Comment by csiefer2** [comment]
@masterleinad Which is what I had at first, before git had a merge conflict.  Grrr...

Now to find a copy of clang-format-8....

**Comment by csiefer2** [comment]
Hah!  Got the format!

**Comment by masterleinad** [comment]
> @masterleinad Apologies for being an idiot, but where in the world do I get that? Clang comes with clang-format, but not clang-format-8 and google is... unhelpful.

On a Mac it's pretty easy with
```
brew install clang-format-8
```
and on `Linux` downloaded `clang-8` from https://releases.llvm.org/download.html#8.0.0.

**Comment by vlkale** [comment]
Thanks for your PR! This fix is obvious and useful.Yes, we use (at this time) clang-format-8 for our Kokkos Tools GitHub CI. This was added only a few months ago. The tips for obtaining clang-format-8 by @masterleinad are what I use, and I will be documenting this on the Kokkos Tools wiki shortly.On Mar 27, 2023, at 4:28 PM, Daniel Arndt ***@***.***> wrote:﻿

@masterleinad Apologies for being an idiot, but where in the world do I get that? Clang comes with clang-format, but not clang-format-8 and google is... unhelpful.

On a Mac it's pretty easy with
brew install clang-format-8

and on Linux downloaded clang-8 from https://releases.llvm.org/download.html#8.0.0.

**Comment by csiefer2** [comment]
@vlkale Any more changes needed, or are you ready to approve this for merge?

**Comment by vlkale** [comment]
> @vlkale Any more changes needed, or are you ready to approve this for merge?

It looks good to me. I am ready to approve though I need either @dalg24 and/or @crtrott to review this. I have requested @dalg24.

**Review by crtrott — APPROVED** [review]

**Review by ajpowelsnl — APPROVED** [review]

**Pull request merged**
