### PR TITLE
Merge for the 3.0 Kokkos Release

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
This gets the tools repo up to date with the new Kokkos. Mostly just code structure changes and new tools

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
And we have a merge conflict? Fantastic

**Comment by crtrott** [comment]
wait a sec.

**Comment by crtrott** [comment]
where is a conflict and I was just doing an update on the build-all script.

**Comment by DavidPoliakoff** [comment]
For a while people were being a little loose with whether they targeted `master` or `develop`

**Comment by DavidPoliakoff** [comment]
Apparently in master we've deleted `src/tools/memory-events/kp_memory_events.cpp`

**Pull request merged**
