### PR TITLE
Fixed units for macOS

### LINKED ISSUE #36: Memory report wrong for Macs
On my Mac laptop, the Kokkos memory profiling values from `getrusage` are off by a factor 1024. This is because `getrusage` uses units of *bytes* on Mac but *kilobytes* on Linux.

### PR DESCRIPTION
**Pull request by jrmadsen**
- Fixed printf warning in kp_hwm.cpp
- Fixes #36

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
@jrmadsen if you change the branch you're targeting to `develop` I'll approve

**Comment by jrmadsen** [comment]
Ah may bad. GTG

**Comment by jrmadsen** [comment]
@DavidPoliakoff

**Comment by DavidPoliakoff** [comment]
Excuse the slow review, somehow thought I had merged this

**Pull request merged**
