### PR TITLE
Update copyright file structure

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Looks good to me, but before merging something like this I'd like a second opinion, since we discussed this design. @dalg24, any thoughts?

**Comment by dalg24** [comment]
> Looks good to me, but before merging something like this I'd like a second opinion, since we discussed this design. @dalg24, any thoughts?

As much as I dislike the current directory structure, the change will probably upset users.

Not a big fan of the argument for the `build-all.sh` script

**Comment by crtrott** [comment]
I take this as a ringing endorsement @dalg24 ...

**Comment by DavidPoliakoff** [comment]
@dalg24 I'll probably do a second pass at what a Kokkos Tools build system should look like at some point in the future.

I'll merge this, it seems good enough

**Pull request merged**
